version: '3.9'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: storedb
      POSTGRES_USER: storeuser
      POSTGRES_PASSWORD: storepass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True

volumes:
  postgres_data:
