# Generated by Django 5.1.7 on 2025-03-24 18:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_date', models.DateField(blank=True, default=None, null=True)),
                ('price', models.IntegerField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('slug', models.SlugField()),
                ('deleted', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
            bases=(models.Model, core.models.Base),
        ),
    ]
