# Generated by Django 5.1.7 on 2025-04-03 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('vat', models.FloatField(default=0.09)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('name', models.CharField(max_length=300)),
                ('total_price', models.IntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=0)),
                ('ref_number', models.CharField(max_length=300)),
                ('authorization_code', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('user_id', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('error', 'Error'), ('done', 'done')], max_length=20)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.invoice')),
            ],
        ),
    ]
